### Program 1

In [1]:
import tensorflow as tf

In [2]:
a1 = tf.constant([4, 3, 2, 1])
a2 = tf.constant([1, 3, 4, 7])

In [8]:
res = tf.multiply(a1, a2)

In [9]:
sess = tf.Session()
print(sess.run(res))
sess.close()

[4 9 8 7]


### Program 2 - Handling Sessions Efficiently

In [11]:
import tensorflow as tf

In [12]:
a1 = tf.constant([4,3,2,1])
a2 = tf.constant([3,1,3,4])

In [13]:
res = tf.multiply(a1,a2)

In [14]:
with tf.Session() as sess:
    finalOutput = sess.run(res)
    print (finalOutput)

[12  3  6  4]


### Understanding Variables

In [71]:
state = tf.Variable(0) # creating a variable with value = 0

In [72]:
one = tf.constant(1) # creating a constant with value = 1
new_value = tf.add(state, one) # add the two values
update = tf.assign(state, new_value) # assigning the added value to state variable

In [79]:
init_op = tf.global_variables_initializer() # global variable initialization operator

In [86]:
with tf.Session() as sess:
    sess.run(init_op) # running initializer
    for _ in range(3):
        sess.run(update) # running update
        print(sess.run(state)) # printing value of state

1
2
3


### Placeholders

- If we want to feed data to tensorflow from outside a model, we have to use placeholders.
- Its like a variable that won't receive its value until a later point.

In [87]:
a = tf.placeholder(tf.float32)

In [92]:
b = a*2 # operation defined using the placeholder
# similar to b = tf.multiply(a, 2)

- Now we need to define and run the session, but since we created a "hole in the model to pass the data, when we initialize the session we are obligated to pass an argument with the data, otherwise we would get an error.

- To pass the data to the model we call the session with an extra argument feed_dict in which we should pass a dictionary with each placeholder name followed by its respective data

In [97]:
with tf.Session() as sess:
    result = sess.run(b, feed_dict = {a:3.5})
    print(sess.run(a, feed_dict = {a:3.0}))
    print(result)

3.0
7.0


- Since data in Tensorflow is passed in form of multidimensional arrays, we can pass any kind of tensor through the placeholders to get the answer to the simple mulitplication operation.

### One Dimension Tensors

In [98]:
import numpy as np
tensor_1d = np.array([1,2,3,4,5])

In [99]:
tensor_1d

array([1, 2, 3, 4, 5])

In [100]:
print(tensor_1d.ndim)

1


In [101]:
print(tensor_1d.shape)

(5,)


In [102]:
print(tensor_1d.dtype)

int32


### Convert to Tensors

- Any numpy array can be converted to a tensor

In [103]:
tensor1d = tf.convert_to_tensor(tensor_1d, dtype = tf.int64)

In [104]:
with tf.Session() as sess:
    print(sess.run(tensor1d))
    print(sess.run(tensor1d[0]))
    print(sess.run(tensor1d[1]))
    

[1 2 3 4 5]
1
2


### Creating a 2D Tensor

In [105]:
array_2d_1  = np.array(np.arange(16).reshape(4,4), dtype = 'int32')

In [112]:
print(array_2d_1) # 2D numpy array

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [107]:
print(array_2d_1.ndim)

2


In [108]:
print(array_2d_1.shape)

(4, 4)


In [109]:
print(array_2d_1.dtype)

int32


In [110]:
tensor_2d_1 = tf.convert_to_tensor(array_2d_1)

In [113]:
with tf.Session() as sess:
    print(sess.run(tensor_2d_1)) # 2d Tensor

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### Matrix operations using Tensors

Initializing the arrays

In [116]:
array_2d_1 = np.array(np.arange(16).reshape(4,4), dtype='int32')
array_2d_2 = np.array(np.arange(16,32).reshape(4,4), dtype='int32')

Converting into tensors

In [117]:
tensor_2d_1 = tf.convert_to_tensor(array_2d_1)
tensor_2d_2 = tf.convert_to_tensor(array_2d_2)

Defining Matrix Operation - Matrix Addition, Multiplication

In [120]:
mat_add = tf.add(tensor_2d_1, tensor_2d_2)

In [121]:
mat_mul = tf.matmul(tensor_2d_1, tensor_2d_2)

Executing the Session

In [123]:
with tf.Session() as sess:
    print("Matrix Addition")
    print(sess.run(mat_add),end = '\n\n')
    print("Matrix Multiplication")
    print(sess.run(mat_mul))

Matrix Addition
[[16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]

Matrix Multiplication
[[ 152  158  164  170]
 [ 504  526  548  570]
 [ 856  894  932  970]
 [1208 1262 1316 1370]]


Determinant of a Matrix

In [136]:
array_2d_1 = np.array(np.arange(16).reshape(4,4), dtype = 'float32')

In [137]:
tensor_2d_1 = tf.convert_to_tensor(array_2d_1)

In [138]:
mat_det = tf.matrix_determinant(tensor_2d_1)

In [139]:
with tf.Session() as sess:
    print(sess.run(mat_det))

0.0


### Linear Regression Example

In [14]:
# Importing the required libraries
import numpy as np
import tensorflow as tf

In [15]:
# Initializing the number of points and the dependent and independent variables.
numPts = 100
x = []
y = []

In [16]:
# Assigning the values for a and b
a = 0.45
b = 0.60

In [17]:
# y = 0.45x + 0.60  --> y = ax + b
# Finally, after gradient descent, the model should also converge to the above values of a and b

In [18]:
# Generate random points for x and y
for i in range(numPts):
    xtemp = np.random.normal(0.0, 0.5)
    ytemp = a*xtemp + b + np.random.normal(0.0,0.1)
    x.append([xtemp])
    y.append([ytemp])

In [19]:
# The linear regression model should converge to an optimal a and b that minimizes the cost function

In [20]:
# Initializing arbitrary values for A and setting b to zero.
A = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.zeros([1]))

In [22]:
# Creating a relationship between x and y
yPred = tf.add(tf.multiply(A,x),b)

In [23]:
learningRate = 0.25

In [24]:
# Cost function is defined. The optimization is done using gradient descent.
# Finally, the model is trained to minimize the cost function.
cost_function = tf.reduce_mean(tf.square(yPred - y))
optimizer = tf.train.GradientDescentOptimizer(learningRate)
train = optimizer.minimize(cost_function)

In [54]:
# Testing the model
NumIter = 50
model = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(model)
    
    for step in range(0,NumIter):
        ModelA = sess.run(A)
        ModelB = sess.run(b)
